<?php
/** @var \Magento\Catalog\Block\Product\View $block */
/** @var \Magento\Framework\Escaper $escaper */
$product = $block->getProduct();
$imageHelper = $this->helper(\Magento\Catalog\Helper\Image::class);
$priceCurrency = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Pricing\PriceCurrencyInterface::class);
?>

<div x-data="productDetail" class="mx-auto md:p-8 pt-4 mt-5" x-cloak>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-5">
        <template x-for="item in items" :key="item.id">
            <div class="flex gap-3">
                <span x-html="item.icons" class="size-6"></span>
                <div class="flex flex-col gap-1">
                    <h3 x-text="item.title" class="text-base md:text-lg font-medium"></h3>
                    <h3 x-text="item.description" class="md:text-base text-[14px] text-gray-400"></h3>
                </div>
            </div>
        </template>
    </div> 
    <div class="flex flex-col justify-center items-center text-center mt-10 gap-2 border-t-2">
        <p class="mt-10 text-2xl font-medium">Versatile and effective Spot Cleaner</p>
        <p class="text-base text-gray-700 pb-5">The VAX SpotWash Home Pet-Design allows for an effortless clean in your home or car.</p>
        <div class="h-[300px] grid grid-cols-3 gap-5">
            <img class="w-full object-cover rounded-lg" 
                 src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/banners/banner2.jpg')) ?>" 
                 alt="Banner promotion" 
                 loading="lazy" />  
            <img class="w-full object-cover rounded-lg" 
                 src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/banners/banner2.jpg')) ?>" 
                 alt="Banner promotion" 
                 loading="lazy" /> 
            <img class="w-full object-cover rounded-lg" 
                 src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/banners/banner2.jpg')) ?>" 
                 alt="Banner promotion" 
                 loading="lazy" />  
        </div>
    </div>
    
    <script>
        document.addEventListener('alpine:init', () => {
            Alpine.data('productDetail', () => ({
                items: [
                    {
                        id: 1,
                        icons: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6"><path stroke-linecap="round" stroke-linejoin="round" d="M6.633 10.25c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 0 1 2.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 0 0 .322-1.672V2.75a.75.75 0 0 1 .75-.75 2.25 2.25 0 0 1 2.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558 .107 1.282 .725 1.282m0 0h3.126c1.026 0 1.945 .694 2.054 1.715 .045 .422 .068 .85 .068 1.285a11.95 11.95 0 0 1-2.649 7.521c-.388 .482-.987 .729-1.605 .729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 0 0-1.423-.23H5.904m10.598-9.75H14.25M5.904 18.5c .083 .205 .173 .405 .27 .602 .197 .4-.078 .898-.523 .898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 0 1-.521-3.507c0-1.553 .295-3.036 .831-4.398C3.387 9.953 4.167 9.5 5 9.5h1.053c .472 0 .745 .556 .5 .96a8.958 8.958 0 0 0-1.302 4.665c0 1.194 .232 2.333 .654 3.375Z" /></svg>',
                        title: '2 Year Guarantee',
                        description: 'Terms & Conditions apply.'
                    },
                    {
                        id: 2,
                        icons: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6"><path stroke-linecap="round" stroke-linejoin="round" d="M8.25 18.75a1.5 1.5 0 0 1-3 0m3 0a1.5 1.5 0 0 0-3 0m3 0h6m-9 0H3.375a1.125 1.125 0 0 1-1.125-1.125V14.25m17.25 4.5a1.5 1.5 0 0 1-3 0m3 0a1.5 1.5 0 0 0-3 0m3 0h1.125c .621 0 1.129-.504 1.09-1.124a17.902 17.902 0 0 0-3.213-9.193 2.056 2.056 0 0 0-1.58-.86H14.25M16.5 18.75h-2.25m0-11.177v-.958c0-.568-.422-1.048-.987-1.106a48.554 48.554 0 0 0-10.026 0 1.106 1.106 0 0 0-.987 1.106v7.635m12-6.677v6.677m0 4.5v-4.5m0 0h-12" /></svg>',
                        title: 'Free Next Day Delivery with DPD',
                        description: 'Most mainland GB addresses. Exclusions apply.'
                    },
                    {
                        id: 3,
                        icons: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6"><path stroke-linecap="round" stroke-linejoin="round" d="M6.633 10.25c .806 0 1.533-.446 2.031-1.08a9.041 9.041 0 0 1 2.861-2.4c .723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 0 0 .322-1.672V2.75a .75 .75 0 0 1 .75-.75 2.25 2.25 0 0 1 2.25 2.25c0 1.152-.26 2.243-.723 3.218-.266 .558 .107 1.282 .725 1.282m0 0h3.126c1.026 0 1.945 .694 2.054 1.715 .045 .422 .068 .85 .068 1.285a11.95 11.95 0 0 1-2.649 7.521c-.388 .482-.987 .729-1.605 .729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 0 0-1.423-.23H5.904m10.598-9.75H14.25M5.904 18.5c .083 .205 .173 .405 .27 .602 .197 .4-.078 .898-.523 .898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 0 1-.521-3.507c0-1.553 .295-3.036 .831-4.398C3.387 9.953 4.167 9.5 5 9.5h1.053c .472 0 .745 .556 .5 .96a8.958 8.958 0 0 0-1.302 4.665c0 1.194 .232 2.333 .654 3.375Z" /></svg>',
                        title: '2 Year Guarantee',
                        description: 'Buy now, Pay later in 3 monthly instalments'
                    },
                ],
             
            }));
           
        });
    </script>
</div>